version: '3.1'
services:

  stats-service:
    build: ewm-stats-service
    image: stats-service
    container_name: StatsServer
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: StatsDB
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  #ewm-service:
    #ports:
     # - "8080:8080"

  #ewm-db:
   # image: postgres:14-alpine