DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS categories cascade;
DROP TABLE IF EXISTS compilations cascade;
DROP TABLE IF EXISTS locations cascade;
DROP TABLE IF EXISTS events cascade;
DROP TABLE IF EXISTS requests cascade;
DROP TABLE IF EXISTS events_compilations cascade;
DROP TABLE IF EXISTS comments cascade;
DROP TABLE IF EXISTS events_comments cascade;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(100) NOT NULL,
    email VARCHAR(256) NOT NULL UNIQUE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL UNIQUE,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title  VARCHAR NOT NULL,
    pinned BOOLEAN NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(120)                      NOT NULL,
    annotation         VARCHAR(2000)                     NOT NULL,
    category_id        BIGINT REFERENCES categories (id) NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE       NOT NULL,
    description        VARCHAR(7000),
    event_date         TIMESTAMP WITHOUT TIME ZONE       NOT NULL,
    initiator_id       BIGINT REFERENCES users (id)      NOT NULL,
    lat                FLOAT                             NOT NULL,
    lon                FLOAT                             NOT NULL,
    paid               BOOLEAN                           NOT NULL,
    participant_limit  BIGINT                                     DEFAULT 0,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN                           NOT NULL DEFAULT TRUE,
    state              VARCHAR(20)                       NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP WITHOUT TIME ZONE   NOT NULL,
    event_id     BIGINT REFERENCES events (id) NOT NULL,
    requester_id BIGINT REFERENCES users (id)  NOT NULL,
    status       VARCHAR(15)                   NOT NULL
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    compilation_id BIGINT REFERENCES compilations (id) NOT NULL,
    event_id       BIGINT REFERENCES events (id)       NOT NULL,
    CONSTRAINT pk_events_compilations PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created   TIMESTAMP WITHOUT TIME ZONE   NOT NULL,
    event_id  BIGINT REFERENCES events (id) NOT NULL,
    author_id BIGINT REFERENCES users (id)  NOT NULL,
    body      VARCHAR(500)                  NOT NULL,
    state     VARCHAR(15)                   NOT NULL
);

CREATE TABLE IF NOT EXISTS events_comments
(
    event_id   BIGINT REFERENCES events (id)   NOT NULL,
    comment_id BIGINT REFERENCES comments (id) NOT NULL,
    CONSTRAINT pk_events_comments PRIMARY KEY (event_id, comment_id)
);