DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS categories cascade;
DROP TABLE IF EXISTS compilations cascade;
DROP TABLE IF EXISTS locations cascade;
DROP TABLE IF EXISTS events cascade;
DROP TABLE IF EXISTS requests cascade;
DROP TABLE IF EXISTS events_compilations cascade;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(100) NOT NULL,
    email VARCHAR(256) NOT NULL UNIQUE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL UNIQUE,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title  VARCHAR NOT NULL,
    pinned BOOLEAN NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title              VARCHAR                           NOT NULL,
    annotation         VARCHAR                           NOT NULL,
    category_id        BIGINT REFERENCES categories (id) NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE       NOT NULL,
    description        TEXT,
    event_date         TIMESTAMP WITHOUT TIME ZONE       NOT NULL,
    initiator_id       BIGINT REFERENCES users (id)      NOT NULL,
    location_id        BIGINT REFERENCES locations (id)  NOT NULL,
    paid               BOOLEAN                           NOT NULL,
    participant_limit  BIGINT                                     DEFAULT 0,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN                           NOT NULL DEFAULT TRUE,
    state              VARCHAR(20)                       NOT NULL,
    views              BIGINT,
    available          BOOLEAN                           NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created      TIMESTAMP WITHOUT TIME ZONE   NOT NULL,
    event_id     BIGINT REFERENCES events (id) NOT NULL,
    requester_id BIGINT REFERENCES users (id)  NOT NULL,
    status       VARCHAR                       NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id),
    FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    compilation_id BIGINT REFERENCES compilations (id) NOT NULL,
    event_id       BIGINT REFERENCES events (id)       NOT NULL,
    CONSTRAINT pk_events_compilations PRIMARY KEY (compilation_id, event_id)
);